import unittest
from swissdutch.dutch import DutchPairingEngine
from swissdutch.constants import FideTitle, Colour, FloatStatus
from swissdutch.pairing import Player

class Test_SwissPairingEngine(unittest.TestCase):
    @staticmethod
    def select_top_seed_colour():
        return Colour.white

    def setUp(self):
        self.maxDiff = None
        self.engine = DutchPairingEngine(self.select_top_seed_colour)

    def test_pair_1st_round(self):
        input_players = (
            Player(name='Bruno',
                   rating=2500,
                   title=FideTitle.IM),
            Player(name='Alice',
                   rating=2500,
                   title=FideTitle.GM),
            Player(name='Carla',
                   rating=2400,
                   title=FideTitle.WGM),
            Player(name='Eloise',
                   rating=2350,
                   title=FideTitle.WIM),
            Player(name='Giorgia',
                   rating=2250,
                   title=FideTitle.FM),
            Player(name='Louise',
                   rating=2150,
                   title=FideTitle.WIM),
            Player(name='Nancy',
                   rating=2100,
                   title=FideTitle.WFM),
            Player(name='Patricia',
                   rating=2050,
                   title=0),
            Player(name='David',
                   rating=2400,
                   title=FideTitle.FM),
            Player(name='Finn',
                   rating=2300,
                   title=FideTitle.FM),
            Player(name='Kevin',
                   rating=2250,
                   title=FideTitle.FM),
            Player(name='Mark',
                   rating=2150,
                   title=FideTitle.CM),
            Player(name='Oskar',
                   rating=2100,
                   title=0),
            Player(name='Robert',
                   rating=2000,
                   title=0)
        )
        expected_players = [
            Player(name='Alice',
                   rating=2500,
                   title=FideTitle.GM,
                   pairing_no=1,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(8,),
                   colour_hist=(Colour.white,)),
            Player(name='Bruno',
                   rating=2500,
                   title=FideTitle.IM,
                   pairing_no=2,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(9,),
                   colour_hist=(Colour.black,)),
            Player(name='Carla',
                   rating=2400,
                   title=FideTitle.WGM,
                   pairing_no=3,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(10,),
                   colour_hist=(Colour.white,)),
            Player(name='David',
                   rating=2400,
                   title=FideTitle.FM,
                   pairing_no=4,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(11,),
                   colour_hist=(Colour.black,)),
            Player(name='Eloise',
                   rating=2350,
                   title=FideTitle.WIM,
                   pairing_no=5,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(12,),
                   colour_hist=(Colour.white,)),
            Player(name='Finn',
                   rating=2300,
                   title=FideTitle.FM,
                   pairing_no=6,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(13,),
                   colour_hist=(Colour.black,)),
            Player(name='Giorgia',
                   rating=2250,
                   title=FideTitle.FM,
                   pairing_no=7,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(14,),
                   colour_hist=(Colour.white,)),
            Player(name='Kevin',
                   rating=2250,
                   title=FideTitle.FM,
                   pairing_no=8,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(1,),
                   colour_hist=(Colour.black,)),
            Player(name='Louise',
                   rating=2150,
                   title=FideTitle.WIM,
                   pairing_no=9,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(2,),
                   colour_hist=(Colour.white,)),
            Player(name='Mark',
                   rating=2150,
                   title=FideTitle.CM,
                   pairing_no=10,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(3,),
                   colour_hist=(Colour.black,)),
            Player(name='Nancy',
                   rating=2100,
                   title=FideTitle.WFM,
                   pairing_no=11,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(4,),
                   colour_hist=(Colour.white,)),
            Player(name='Oskar',
                   rating=2100,
                   title=0,
                   pairing_no=12,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(5,),
                   colour_hist=(Colour.black,)),
            Player(name='Patricia',
                   rating=2050,
                   title=0,
                   pairing_no=13,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(6,),
                   colour_hist=(Colour.white,)),
            Player(name='Robert',
                   rating=2000,
                   title=0,
                   pairing_no=14,
                   score=0,
                   float_status=FloatStatus.none,
                   opponents=(7,),
                   colour_hist=(Colour.black,))
        ]
        
        result_players = self.engine.pair_round(1, input_players)
        self.assertEqual(result_players, expected_players)