import unittest
from swissdutch.dutch import DutchPairingEngine
from swissdutch.constants import FideTitle, Colour, FloatStatus
from swissdutch.pairing import PairingCard

class Test_SwissPairingEngine(unittest.TestCase):
    @staticmethod
    def select_top_seed_colour():
        return Colour.white

    def setUp(self):
        self.maxDiff = None
        self.engine = DutchPairingEngine(self.select_top_seed_colour)

    def test_pair_1st_round(self):
        input_pairing_cards = (
            PairingCard(name='Bruno',
                        rating=2500,
                        title=FideTitle.IM),
            PairingCard(name='Alice',
                        rating=2500,
                        title=FideTitle.GM),
            PairingCard(name='Carla',
                        rating=2400,
                        title=FideTitle.WGM),
            PairingCard(name='Eloise',
                        rating=2350,
                        title=FideTitle.WIM),
            PairingCard(name='Giorgia',
                        rating=2250,
                        title=FideTitle.FM),
            PairingCard(name='Louise',
                        rating=2150,
                        title=FideTitle.WIM),
            PairingCard(name='Nancy',
                        rating=2100,
                        title=FideTitle.WFM),
            PairingCard(name='Patricia',
                        rating=2050,
                        title=0),
            PairingCard(name='David',
                        rating=2400,
                        title=FideTitle.FM),
            PairingCard(name='Finn',
                        rating=2300,
                        title=FideTitle.FM),
            PairingCard(name='Kevin',
                        rating=2250,
                        title=FideTitle.FM),
            PairingCard(name='Mark',
                        rating=2150,
                        title=FideTitle.CM),
            PairingCard(name='Oskar',
                        rating=2100,
                        title=0),
            PairingCard(name='Robert',
                        rating=2000,
                        title=0)
        )
        expected_pairing_cards = [
            PairingCard(name='Alice',
                        rating=2500,
                        title=FideTitle.GM,
                        pairing_no=1,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(8,),
                        colour_hist=(Colour.white,)),
            PairingCard(name='Bruno',
                        rating=2500,
                        title=FideTitle.IM,
                        pairing_no=2,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(9,),
                        colour_hist=(Colour.black,)),
            PairingCard(name='Carla',
                        rating=2400,
                        title=FideTitle.WGM,
                        pairing_no=3,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(10,),
                        colour_hist=(Colour.white,)),
            PairingCard(name='David',
                        rating=2400,
                        title=FideTitle.FM,
                        pairing_no=4,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(11,),
                        colour_hist=(Colour.black,)),
            PairingCard(name='Eloise',
                        rating=2350,
                        title=FideTitle.WIM,
                        pairing_no=5,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(12,),
                        colour_hist=(Colour.white,)),
            PairingCard(name='Finn',
                        rating=2300,
                        title=FideTitle.FM,
                        pairing_no=6,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(13,),
                        colour_hist=(Colour.black,)),
            PairingCard(name='Giorgia',
                        rating=2250,
                        title=FideTitle.FM,
                        pairing_no=7,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(14,),
                        colour_hist=(Colour.white,)),
            PairingCard(name='Kevin',
                        rating=2250,
                        title=FideTitle.FM,
                        pairing_no=8,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(1,),
                        colour_hist=(Colour.black,)),
            PairingCard(name='Louise',
                        rating=2150,
                        title=FideTitle.WIM,
                        pairing_no=9,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(2,),
                        colour_hist=(Colour.white,)),
            PairingCard(name='Mark',
                        rating=2150,
                        title=FideTitle.CM,
                        pairing_no=10,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(3,),
                        colour_hist=(Colour.black,)),
            PairingCard(name='Nancy',
                        rating=2100,
                        title=FideTitle.WFM,
                        pairing_no=11,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(4,),
                        colour_hist=(Colour.white,)),
            PairingCard(name='Oskar',
                        rating=2100,
                        title=0,
                        pairing_no=12,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(5,),
                        colour_hist=(Colour.black,)),
            PairingCard(name='Patricia',
                        rating=2050,
                        title=0,
                        pairing_no=13,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(6,),
                        colour_hist=(Colour.white,)),
            PairingCard(name='Robert',
                        rating=2000,
                        title=0,
                        pairing_no=14,
                        score=0,
                        float_status=FloatStatus.none,
                        opponents=(7,),
                        colour_hist=(Colour.black,))
        ]
        
        result_pairing_cards = self.engine.pair_round(1, input_pairing_cards)
        self.assertEqual(result_pairing_cards, expected_pairing_cards)